###  Makefile for C/Splint tutorial

include Makefile.constants

all:
	cd chapter1; $(MAKE) all;
	cd chapter2; $(MAKE) all;
	cd chapter3; $(MAKE) all;
	cd chapter4; $(MAKE) all;

compile_check:
	cd chapter1; $(MAKE) compile_check;
	cd chapter2; $(MAKE) compile_check;
	cd chapter3; $(MAKE) compile_check;
	cd chapter4; $(MAKE) compile_check;
